[package]
name = "wasm-fanout"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio_wasi = { version = "1.25", features = ["rt", "macros", "net", "time", "io-util"]}
wasmedge_http_req = "0.9.0"
chrono = "0.4.24"